### ISSUE TITLE
How to raise test coverage on parameters passed to NoOpLogger 

### ISSUE THREAD

**Issue by caoilte** [typelevel/log4cats#272]
I'm failing to meet 100% coverage requirements in a module because the call by name string inside a log effect never gets executed. Would it be reasonable to make the no-op logger execute the passed in strings or to provide an option that allowed it?

**Comment by ChristopherDavenport** [comment]
We can void that argument. 

```scala
private def void(args: Any*): Unit = {
   val _ = args
   ()
}
```

If we put that in place would that fix your coverage issue?

**Comment by ant8e** [comment]
I ran into the same problem today. The solution proposed by @ChristopherDavenport seems sensible. Would a PR along these lines be acceptable?
