### ISSUE TITLE
Release log4cats-scribe with scala 2.13 and scalajs 2.13 support.

### ISSUE THREAD

**Issue by busti** [typelevel/log4cats#309]
Scribe has been compatible with scala 2.13 since release 2.7.8 https://github.com/outr/scribe/issues/114  

A log4cats release targeting those versions is missing from maven.  
I personally would like to use log4cats with scribe in a scalajs environment.

**Comment by danicheg** [comment]
`log4cats` has published versions for ScalaJS and Scala 2.13.
