### ISSUE TITLE
Release for version 1.2.0 not available on Maven

### ISSUE THREAD

**Issue by felixbr** [typelevel/log4cats#404]
Hi 👋

Here on Github it says 1.2.0 was released over a week ago but I cannot find it on Maven. Is this intentional or did something break the release? 🙂

https://mvnrepository.com/artifact/io.chrisdavenport/log4cats-core
https://mvnrepository.com/artifact/io.chrisdavenport/log4cats-slf4j

Cheers
~ Felix

edit: The issue number is really fitting 😅

CC @rossabaker

**Comment by rossabaker** [comment]
> edit: The issue number is really fitting sweat_smile

:laughing: 

Starting with 1.2.0, it moved to `org.typelevel`.  The Maven name and top level package changed.  It should be otherwise source compatible.

**Comment by felixbr** [comment]
Ah, that's good to hear. Maybe a note in the release notes could avoid confusion for other people like me that blindly update version numbers 🙂

**Comment by rossabaker** [comment]
It was noted in the release candidate, but I'll add a special note since it was confusing.
