### ISSUE TITLE
Publish versionScheme

### ISSUE THREAD

**Issue by majk-p** [typelevel/log4cats#423]
With SBT 1.5.0 now in place, [`versionScheme`](https://www.scala-sbt.org/1.x/docs/Publishing.html#Version+scheme) gained importance as it's the source of truth when identifying eviction warnings. Can we please add it to `build.sbt`? 
What would be the best value for that? `semver-spec` looks reasonable IMO

**Comment by rossabaker** [comment]
I thought sbt-spiewak gave us this for free?  I haven't had to add this to any of my other projects.  Would like to have it, but I don't know why it wouldn't be there already.

**Comment by majk-p** [comment]
Sorry, I've missed that. I took a look at old artiffacts, `sbt-spiewak` does that so the issue can be closed
