### ISSUE TITLE
Streamline adding context to structured loggers

### ISSUE THREAD

**Issue by nigredo-tori** [typelevel/log4cats#424]
At the moment, to add some context to the logger we have to do this:
```scala
StructuredLogger.withContext(logger)(Map("foo" -> 123.show))
// Or
SelfAwareStructuredLogger.withContext(logger)(Map("foo" -> 123.show))
```
This is noisy. Also note that the two versions produce subtly different results - the first one "loses" the logger's self-awareness. 

Instead, I'd like to be able to write something like
```scala
logger.withContext(Map("foo" -> "123"))
// or, better yet
logger.withContext("foo" -> "123"))
```
and have it return `StructuredLogger` or `SelfAwareStructuredLogger` depending on the `logger`'s type.

**Comment by lorandszakacs** [comment]
Closed in #425
