### ISSUE TITLE
Blocking Slf4j Logger Backer

### ISSUE THREAD

**Issue by ChristopherDavenport** [typelevel/log4cats#440]
Not all Slf4j Backends are async. As a result we should provide a blocking consructor so that users of those backends don't do their blocking logging on their computer pool which is wasteful.

Noted from Discord.

Impl can be the exact same as current with `Sync[F].delay -> Sync[F].blocking`

**Comment by chaitanyawaikar** [comment]
I can pick this up.

**Comment by armanbilge** [comment]
> What about changing current implementation for using `Sync[F].suspend` with default for `Delay`

That sounds like a good solution.

> implement as a new method inside `Slf4jLogger`?

👍

**Comment by diogocanut** [comment]
I think this one can be closed already, solved at #762 .
