### ISSUE TITLE
Microsite Fix

### ISSUE THREAD

**Issue by ChristopherDavenport** [typelevel/log4cats#444]
gh-pages branch is not being published, and or its just not pushing to gh-pages branch presently. 

Its been 2 years since a microsite release. We should fix that.

Working Microsite setup
https://github.com/davenverse/mapref/blob/main/build.sbt

https://github.com/davenverse/mapref/blob/main/build.sbt#L86 - Needs to be typelevel

**Comment by chaitanyawaikar** [comment]
I can pick this up.

**Comment by danicheg** [comment]
Fixed within #592.
