### ISSUE TITLE
Backport #629 (LoggerFactory) to Cats Effect 2 compatible release series.

### ISSUE THREAD

**Issue by FunFunFine** [typelevel/log4cats#655]
A little bit of important context: I work at one of the largest functional scala companies in Europe; most of the code still works with Cats Effect 2. We would totally love to migrate to CE3, but this process is long and tedious in our case. 

So, recently log4cats got several exciting updates (e.g #629 or #), and it would be cool if those changes were backported to some CE2 compatible version.

**Comment by rossabaker** [comment]
I can cut a release if you (or someone) can do the backports.

**Comment by FunFunFine** [comment]
> I can cut a release if you (or someone) can do the backports.

I made #656.

(I have never backported anything before, so I just created a branch off `series/1.x` and cherry-picked desired commits. Feel free to tell me if something is not right.)

**Comment by rossabaker** [comment]
That strategy is how I would do it.

**Comment by danicheg** [comment]
[v1.7.0](https://github.com/typelevel/log4cats/releases/tag/v1.7.0) is on-air.
