### ISSUE TITLE
Implement a Scala.js `ConsoleLogger`

### ISSUE THREAD

**Issue by armanbilge** [typelevel/log4cats#680]
There's currently no "default" logging backend for Scala.js, but it should be easy to add one based on the JavaScript `console` APIs. Technically `console` is not part of core JavaScript, but it is specced and is fairly standard across Node.js and browsers.

- https://console.spec.whatwg.org/
- https://developer.mozilla.org/en-US/docs/Web/API/console
- https://nodejs.org/api/console.html

I'm not a maintainer on this repo so if someone works on this or has questions please make sure to ping me :)

**Comment by armanbilge** [comment]
Here's a partial facade for the `console` APIs. We should inline it instead of adding a dependency to scala-js-dom because that dependency makes sense only for browsers.

https://github.com/scala-js/scala-js-dom/blob/51a807cc04ea134ece030d6d4005a8ce30c1de99/dom/src/main/scala/org/scalajs/dom/Console.scala

**Comment by 2chilled** [comment]
@danicheg It seems like there is no release including this functionality available yet. Can we change that? Would be great!

**Comment by armanbilge** [comment]
Yes, I'd love a release with this too. Until then, there is a snapshot.
https://s01.oss.sonatype.org/content/repositories/snapshots/org/typelevel/log4cats-js-console_sjs1_3/2.5.0-99-e87a0cd-SNAPSHOT/

**Comment by rossabaker** [comment]
I just created a 3.6.0 milestone with the things that are almost ready, and we can get a new release.
