### ISSUE TITLE
Is there big performance hit calling <MyLogger>[F].create on every function call

### ISSUE THREAD

**Issue by Marcus-Rosti** [typelevel/log4cats#712]
Is it best practice to create a logger on every function call? I'm assuming that has a performance it though

**Comment by danicheg** [comment]
> Is there big performance hit calling <MyLogger>[F].create on every function call

Despite that `slf4j` caches logger instances internally, I'd say there is some performance hit anyway.

**Comment by Marcus-Rosti** [comment]
Thanks for the answers! I'm satisfied!
