### ISSUE TITLE
Publish `v2.6.0`

### ISSUE THREAD

**Issue by danicheg** [typelevel/log4cats#745]
It turns out, we have got a lot of new cool stuff since the last release. So I drafted the `v2.6.0` release notes https://github.com/typelevel/log4cats/releases/edit/untagged-d43a243eee78bfc1ddad. Any objections to having it published?

**Comment by rossabaker** [comment]
No objections, and thanks!

**Comment by danicheg** [comment]
https://github.com/typelevel/log4cats/releases/tag/v2.6.0
