### ISSUE TITLE
Release latest dependency updates

### ISSUE THREAD

**Issue by howyp** [typelevel/log4cats#832]
Hi, would be great if we could get a release of this lib, lots of updates have happened since 2.6.0. Thanks!

**Comment by danicheg** [comment]
Yeah, it's been a while since the last release. Not only have the dependencies been updated, but we've even got some new features. @typelevel/log4cats thoughts?

**Comment by danicheg** [comment]
https://github.com/typelevel/log4cats/releases/tag/v2.7.0
Artifacts should appear in Maven Central in 4-8 hours normally.
